version: "3.9"

services:
  goapp:
    image: akira2002/check-stock:latest
    build: .
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
      restart_policy:
        condition: on-failure

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
      restart_policy:
        condition: on-failure

